@startuml database

entity "Users" as users {
    * user_id   : INTEGER <<PK>>
    --
    email    : TEXT
    password    : TEXT
    lPlate      : TEXT
}

entity "Auth" as auth {
    * user_id   : INTEGER <<PK>>
    --
    lastAuth    : INTEGER
    created_at  : INTEGER
}

entity "Parking" as parking {
    * park_id   : INTEGER <<PK>>
    --
    tupe        : INTEGER
    start_date  : INTEGER
    end_date    : INTEGER
    slot_id     : INTEGER <<FK>>
    user_id     : INTEGER <<FK>>
    lPlate      : TEXT
}

users }o--o{ parking : "user_id"
users ||--|| auth   : "user_id"
@enduml